### ISSUE TITLE
script to shuffle images in a folder?

### ISSUE THREAD

**Issue by notaaryansh** [Vedant-K1/AutoSort#3] opened 2022-10-02 08:55 UTC
Manually collecting data leads to a lot of patterns, this will limit the ml/dl model from learning properly, proposing a script to randomize/shuffle the images inside a directory

**Comment by Vedant-K1** [comment] 2022-10-02 09:12
um... actually that won't be needed, because the ML, deep learning model should learn from some other data-set. what the aim of ml-dl is to sort the pictures into categories like people, monuments, buildings, landscapes, sceneries, etc. 
or,
what you can do is train some model which will classify the image into such categories and automatically store them into those folders. 
(Training the data is not the main aim, creating an application is)
I think the issue is solved? Should i close it?

**Comment by notaaryansh** [comment] 2022-10-02 09:48
yeah issue solved!

**Closed as completed** 2022-10-02 10:07 UTC
